services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_app
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  app:
    build: .
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: todo_app
    networks:
      - app_network
    ports:
      - "8080:8080"

networks:
  app_network:

volumes:
  mysql_data:
